/**
 * Regenerates `patch.ts` from the fixture's file contents by building a throwaway
 * git repository and asking git for the diff.
 *
 * The harness feeds that patch through the same parser the real app uses, so the
 * fixture has to be genuine git output rather than a hand-written approximation.
 *
 *   node --experimental-strip-types dev-harness/generatePatch.ts
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SUMMARY, VERSIONS } from "./fixture.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repo = mkdtempSync(join(tmpdir(), "tk-review-fixture-"));
const git = (...args: string[]) => execFileSync("git", args, { cwd: repo, encoding: "utf8" });

const write = (relative: string, contents: string) => {
  const target = join(repo, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
};

try {
  git("init", "--initial-branch=main", "--quiet");
  git("config", "user.email", "fixture@example.com");
  git("config", "user.name", "Fixture");

  // Base commit: every file that exists on the old side, under its old name.
  for (const file of SUMMARY.files) {
    const versions = VERSIONS[file.path];
    if (versions?.old != null) write(file.oldPath ?? file.path, versions.old);
  }
  // A binary file needs bytes git will refuse to treat as text.
  const binary = SUMMARY.files.find((file) => file.isBinary);
  if (binary) {
    writeFileSync(join(repo, ".gitattributes"), "");
    mkdirSync(dirname(join(repo, binary.path)), { recursive: true });
    writeFileSync(join(repo, binary.path), Buffer.from([0, 1, 2, 3, 4, 5]));
  }
  git("add", "-A");
  git("commit", "--quiet", "-m", "base");

  git("checkout", "--quiet", "-b", "feature");
  for (const file of SUMMARY.files) {
    if (file.isBinary) continue;
    const versions = VERSIONS[file.path];
    if (versions?.new != null) write(file.path, versions.new);
    // A deleted file, or the vacated source of a rename.
    if (versions?.new == null && versions?.old != null) {
      rmSync(join(repo, file.oldPath ?? file.path), { force: true });
    }
    if (file.oldPath) rmSync(join(repo, file.oldPath), { force: true });
  }
  if (binary) writeFileSync(join(repo, binary.path), Buffer.from([9, 8, 7, 6, 5, 4, 3]));
  git("add", "-A");
  git("commit", "--quiet", "-m", "feature work");

  const patch = git(
    "diff",
    "--find-renames",
    "--no-ext-diff",
    "--no-color",
    "-U3",
    "main..feature",
  );

  // Report git's own counts so the fixture's summary can match the patch instead
  // of drifting from it.
  console.log("--- numstat ---");
  console.log(git("diff", "--numstat", "--find-renames", "main..feature"));
  console.log("--- name-status ---");
  console.log(git("diff", "--name-status", "--find-renames", "main..feature"));

  const escaped = patch.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  writeFileSync(
    join(here, "patch.ts"),
    `// Generated by generatePatch.ts — real \`git diff\` output for the fixture.\n` +
      `// Regenerate with: node --experimental-strip-types dev-harness/generatePatch.ts\n` +
      `export const PATCH = \`${escaped}\`;\n`,
  );
  console.log(`wrote patch.ts (${patch.length} bytes)`);
} finally {
  rmSync(repo, { recursive: true, force: true });
}
