// Generated by generatePatch.ts — real `git diff` output for the fixture.
// Regenerate with: node --experimental-strip-types dev-harness/generatePatch.ts
export const PATCH = `diff --git a/migrations/0007_add_reviews_table.sql b/migrations/0007_add_reviews_table.sql
index 458b7c0..2f6bc19 100644
--- a/migrations/0007_add_reviews_table.sql
+++ b/migrations/0007_add_reviews_table.sql
@@ -3,7 +3,11 @@ create table reviews (
   repo_id uuid not null references repos (id),
   base_ref text not null,
   compare_ref text not null,
+  merge_base text not null,
+  viewed_paths text[] not null default '{}',
   created_at timestamptz not null default now()
 );
 
 create index reviews_repo_id_idx on reviews (repo_id);
+
+create index reviews_created_at_idx on reviews (created_at desc);
diff --git a/src-tauri/icons/icon.png b/src-tauri/icons/icon.png
index d43e6e8..816cb6d 100644
Binary files a/src-tauri/icons/icon.png and b/src-tauri/icons/icon.png differ
diff --git a/src/components/DiffViewer/DiffViewer.tsx b/src/components/DiffViewer/DiffViewer.tsx
index 01bdc6f..6f0d0a0 100644
--- a/src/components/DiffViewer/DiffViewer.tsx
+++ b/src/components/DiffViewer/DiffViewer.tsx
@@ -1,17 +1,36 @@
-import { useEffect, useState } from "react";
+import { type DiffFileInput, MultiFileDiff } from "@pierre/diffs/react";
+import { useEffect, useMemo, useState } from "react";
 import type { FileChange } from "../../ipc/git";
 import css from "./DiffViewer.module.css";
 
 export function DiffViewer({ file }: { file: FileChange }) {
-  const [contents, setContents] = useState<string | null>(null);
+  const [versions, setVersions] = useState<FileVersions | null>(null);
+  const layout = useReviewStore((state) => state.layout);
 
   useEffect(() => {
-    loadFile(file.path).then(setContents);
+    let cancelled = false;
+    getFileVersions(file).then((next) => {
+      if (!cancelled) setVersions(next);
+    });
+    return () => {
+      cancelled = true;
+    };
   }, [file.path]);
 
-  if (contents === null) {
+  // DiffFileInput requires at least one side, so narrow before rendering.
+  const input = useMemo<DiffFileInput | null>(() => {
+    if (!versions) return null;
+    const oldFile = versions.old !== null ? { name: file.path, contents: versions.old } : null;
+    const newFile = versions.new !== null ? { name: file.path, contents: versions.new } : null;
+    if (oldFile && newFile) return { oldFile, newFile };
+    if (newFile) return { oldFile: null, newFile };
+    if (oldFile) return { oldFile, newFile: null };
+    return null;
+  }, [versions, file.path]);
+
+  if (!input) {
     return <p className={css.message}>Loading…</p>;
   }
 
-  return <pre className={css.plain}>{contents}</pre>;
+  return <MultiFileDiff {...input} options={{ diffStyle: layout }} />;
 }
diff --git a/src/ipc/git.ts b/src/ipc/git.ts
new file mode 100644
index 0000000..80c3ebf
--- /dev/null
+++ b/src/ipc/git.ts
@@ -0,0 +1,17 @@
+import { invoke } from "@tauri-apps/api/core";
+
+export type ChangeStatus = "added" | "modified" | "deleted" | "renamed";
+
+export interface FileChange {
+  path: string;
+  oldPath: string | null;
+  status: ChangeStatus;
+  additions: number;
+  deletions: number;
+  isBinary: boolean;
+}
+
+export const gitApi = {
+  selectRepo: (path: string) => invoke<RepoInfo>("select_repo", { path }),
+  listBranches: (root: string) => invoke<Branch[]>("list_branches", { root }),
+};
diff --git a/src/legacy/OldViewer.tsx b/src/legacy/OldViewer.tsx
deleted file mode 100644
index 0b42d1c..0000000
--- a/src/legacy/OldViewer.tsx
+++ /dev/null
@@ -1,14 +0,0 @@
-import css from "./OldViewer.module.css";
-
-// Superseded by DiffViewer, which renders through @pierre/diffs.
-export function OldViewer({ patch }: { patch: string }) {
-  return (
-    <div className={css.wrap}>
-      {patch.split("\\n").map((line, index) => (
-        <div key={index} className={css.line}>
-          {line}
-        </div>
-      ))}
-    </div>
-  );
-}
diff --git a/src/lib/status.ts b/src/lib/fileChange.ts
similarity index 65%
rename from src/lib/status.ts
rename to src/lib/fileChange.ts
index de96549..56c760b 100644
--- a/src/lib/status.ts
+++ b/src/lib/fileChange.ts
@@ -4,6 +4,8 @@ export const STATUS_META = {
   deleted: { letter: "D", label: "Deleted" },
   renamed: { letter: "R", label: "Renamed" },
   copied: { letter: "C", label: "Copied" },
+  typeChanged: { letter: "T", label: "Type changed" },
+  unmerged: { letter: "U", label: "Unmerged" },
 };
 
 export function splitPath(path: string) {
@@ -11,3 +13,8 @@ export function splitPath(path: string) {
   if (index === -1) return { dir: "", name: path };
   return { dir: path.slice(0, index + 1), name: path.slice(index + 1) };
 }
+
+export function formatBytes(bytes: number) {
+  if (bytes < 1024) return \\\`\\\${bytes} B\\\`;
+  return \\\`\\\${(bytes / 1024).toFixed(1)} KB\\\`;
+}
`;
